name: kiss_color
description: A Flutter package that provides a flexible and maintainable way to manage semantic color systems in your application.
version: 0.5.1
homepage: https://github.com/WAMF/kiss_color

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
